version: "3.8"
services:
  web:
    build:
      context: .
    ports:
      - 5000:5000
    command: python manage.py run -h 0.0.0.0
    container_name: ${FLASK_APP}
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: ${FLASK_APP}_db
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # portainer:
  #   image: portainer/portainer-ce
  #   container_name: portainer
  #   restart: always
  #   ports:
  #     - "${PORTAINER_PORT}:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db:
