version: "3.8"
services:
  web:
    build:
      context: .
    ports:
      - 5000:5000
    command: python manage.py run -h 0.0.0.0
    container_name: ${FLASK_APP}
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
