version: "2.1"
services:
  base:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env.dev
    command: "false"

  web:
    extends:
      service: base
    ports:
      - 5000:5000
    command: python manage.py run -h 0.0.0.0
    container_name: ${FLASK_APP}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    extends:
      service: base
    command: python manage.py db upgrade
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
