"""empty message

Revision ID: 62f99f6c1ede
Revises: 9c13045e86d9
Create Date: 2022-01-11 00:36:44.398811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f99f6c1ede'
down_revision = '9c13045e86d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(), nullable=True))
    op.add_column('post', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('post', 'subject')
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post', 'body')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
